### ISSUE TITLE
TuxGuitar won't open on my computer/laptop anymore

### ISSUE THREAD

**Issue by LeeManLemon** [helge17/tuxguitar#179] opened 2023-12-24 10:04 UTC
I will preface this with the fact that I am running on Windows 10 on my pc and Windows 11 on my laptop as of right now.

I have tried to open and run TuxGuitar on both my laptop and on my computer, however, I cannot open the applications, this hasn't been a problem before, as a matter of fact I have ~20-30 full songs written and saved as .tg files and the application has been on my computer since approximately November of last year. Whenever I click on the "Launch TuxGuitar" application, nothing appears to happen and I am unsure what to do to solve this issue.

Wtf do i do?

**Comment by guiv42** [comment] 2023-12-24 10:52
Hi.
First of all, no need to stress about your work, there's no reason you can not succeed. Many users are running this version of TuxGuitar on Windows, so that should be ok.
> the application has been on my computer since approximately November of last year

So I understand you're not using the last version. I suggest that you switch to version 1.6.0, so we can provide efficient support. First, try to uninstall TuxGuitar from your machine (from Windows control panel?).
Then try to install v1.6.0 with [this installer](https://github.com/helge17/tuxguitar/releases/download/1.6.0/tuxguitar-1.6.0-windows-swt-x86_64-installer.exe). If it does not launch correctly, try to run it from a powershell.
If for some reason it does not work, there is still the possibility to use the [standalone version](https://github.com/helge17/tuxguitar/releases/download/1.6.0/tuxguitar-1.6.0-windows-swt-x86_64.zip): unzip it somewhere and run the extracted "tuxguitar.bat".
Keep us informed, I don't doubt there is a solution

**Comment by downToHell** [comment] 2024-02-28 07:49
I can verify what @LeeManLemon said. On my Mac neither of the new versions open. I've got a MacBook Air 13" (Early 2014) with macOs 11.7.10 installed on it. I tried to open the official build 1.6.1 of TuxGuitar and both swt and jfx versions of the latest Snapshot 2024-02-26 (at this point) but none of them worked

**Comment by helge17** [comment] 2024-02-28 17:02
I cannot reproduce the problem on my systems. The new versions can be opened under Windows and MacOS.

Maybe you have some "old" TuxGuitar settings? You can try deleting the configuration folder:

- Windows: `%USERPROFILE%\AppData\Roaming\tuxguitar`
- MacOS: `$HOME/Library/Application Support/tuxguitar`

Otherwise, as @guiv42 already suggested, you can run TuxGuitar from the command line, you might get some meaningful output that could tell us more about the problem:

- Windows (cmd or PowerShell): `cd folder\where\you\installed\tuxguitar`, then `tuxguitar.exe` or `tuxguitar.bat`
- MacOS (Terminal app): `cd folder/where/you/installed/tuxguitar.app/Contents/MacOS`, then `./tuxguitar.sh`

**Comment by downToHell** [comment] 2024-02-28 18:27
@helge17 for some reason it works now on my Mac. Although I didn't really change anything apart from the fact that I run it from the command line for once...

**Comment by guiv42** [comment] 2024-03-21 21:28
@LeeManLemon : any news?
Since your issue has been raised on an old version, and we cannot reproduce, currently there's no way for this issue to make any progress.

**Comment by xga-cga** [comment] 2024-04-15 19:01
I had a similiar problem on the raspberry pi 4 version of Tux Guitar, I noticed on Sunday April 14, 2024 after using pi apps, parts of it opened the gui, the buttons didn't work but it was more usable.  It seemed to be due to an update on raspberry pi apps on 4april/11th/2024 after checking discord.  Maybe Java is a problem for you...  There were new releases for many platforms on 4/10/2024.  Some portable and with openjava:  https://github.com/helge17/tuxguitar/releases/  Depending on your hardware you could also try 32-bit.

**Comment by guiv42** [comment] 2024-05-06 07:18
Closing issue, as there is no possible way for this issue to progress.
@LeeManLemon : try to update TuxGuitar version. If problem persist, feel free to re-open issue.

**Closed by guiv42** 2024-05-06 07:18 UTC
Labels: question
