### ISSUE TITLE
Dark theme cannot be displayed normally.

### ISSUE THREAD

**Issue by Hgnim** [helge17/tuxguitar#550] opened 2024-10-12 05:53 UTC
![屏幕截图 2024-10-12 134908](https://github.com/user-attachments/assets/500a8ebd-ee9d-4f36-807b-82d3cd50ce45)
When I change the program theme to a theme about dark colors, the program will appear as shown in the picture.
I have tried restarting my computer, but it has not changed.

**Comment by guiv42** [comment] 2024-10-12 09:38
Already known problem. If you're on Linux or macOS then set up your desktop in dark mode globally.
If you're on Windows it does not work.
Closing issue: duplicate of #27 (like #465, #473, #514)

**Closed by guiv42** 2024-10-12 09:38 UTC
