### ISSUE TITLE
Stuck on splash screen on Wayland

### ISSUE THREAD

**Issue by ojsl1** [helge17/tuxguitar#323] opened 2024-04-05 12:20 UTC
OS: Manjaro Linux
DE: KDE Plasma 6
Kernel: Linux 6.8.4

Two weeks ago following [INSTALL.md#generic-gnulinux](https://github.com/helge17/tuxguitar/blob/master/INSTALL.md#generic-gnulinux) I compiled this with the commit f811c19 and java-21-openjdk. It worked fine on X11.

But now trying it again on Wayland it gets stuck on the splash screen with the following errors (still works without any errors on X11).

I don't use this program often enough to troubleshoot this, i'll try with the newest commits if requested.

```
Gdk-Message: 14:52:49.782: Unable to load double_arrow from the cursor theme
org.eclipse.swt.SWTError: No more handles
        at org.eclipse.swt.SWT.error(SWT.java:4737)
        at org.eclipse.swt.SWT.error(SWT.java:4626)
        at org.eclipse.swt.SWT.error(SWT.java:4597)
        at org.eclipse.swt.graphics.Cursor.<init>(Cursor.java:217)
        at org.eclipse.swt.widgets.Display.getSystemCursor(Display.java:2860)
        at org.herac.tuxguitar.ui.swt.resource.SWTCursor.getCursor(SWTCursor.java:37)
        at org.herac.tuxguitar.ui.swt.widget.SWTControl.setCursor(SWTControl.java:211)
        at org.herac.tuxguitar.app.view.main.TGWindowDivider.createDivider(TGWindowDivider.java:29)
        at org.herac.tuxguitar.app.view.main.TGWindow.createShellComposites(TGWindow.java:94)
        at org.herac.tuxguitar.app.view.main.TGWindow.createWindow(TGWindow.java:60)
        at org.herac.tuxguitar.app.TuxGuitar.startUIContext(TuxGuitar.java:135)
        at org.herac.tuxguitar.app.TuxGuitar.access$100(TuxGuitar.java:69)
        at org.herac.tuxguitar.app.TuxGuitar$1$1.run(TuxGuitar.java:124)
        at org.herac.tuxguitar.app.synchronizer.TGSynchronizerControllerImpl$1$1.run(TGSynchronizerControllerImpl.java:29)
        at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
        at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
        at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4857)
        at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4409)
        at org.herac.tuxguitar.ui.swt.SWTApplication.start(SWTApplication.java:64)
        at org.herac.tuxguitar.app.TuxGuitar.createUIContext(TuxGuitar.java:117)
        at org.herac.tuxguitar.app.TuxGuitar.createApplication(TuxGuitar.java:102)
        at org.herac.tuxguitar.app.TGMainSingleton.launchTuxGuitar(TGMainSingleton.java:57)
        at org.herac.tuxguitar.app.TGMainSingleton.launchSingleton(TGMainSingleton.java:45)
        at org.herac.tuxguitar.app.TGMainSingleton.main(TGMainSingleton.java:35)
Exception in thread "Thread-1" java.lang.NullPointerException: Cannot invoke "org.herac.tuxguitar.action.TGActionContext.setAttribute(String, Object)" because "actionContext" is null
        at org.herac.tuxguitar.editor.action.TGActionProcessor.appendAttributes(TGActionProcessor.java:67)
        at org.herac.tuxguitar.editor.action.TGActionProcessor.fillActionContext(TGActionProcessor.java:57)
        at org.herac.tuxguitar.editor.action.TGActionProcessor.processOnCurrentThread(TGActionProcessor.java:75)
        at org.herac.tuxguitar.editor.action.TGActionProcessor.processOnCurrentThread(TGActionProcessor.java:88)
        at org.herac.tuxguitar.editor.action.TGActionProcessor$1.run(TGActionProcessor.java:98)
        at org.herac.tuxguitar.thread.TGPooledThreadHandler.processNext(TGPooledThreadHandler.java:66)
        at org.herac.tuxguitar.thread.TGPooledThreadHandler.run(TGPooledThreadHandler.java:86)
        at java.base/java.lang.Thread.run(Thread.java:1570)
java.lang.NullPointerException: Cannot invoke "org.herac.tuxguitar.util.TGLock.tryLock()" because "lock" is null
        at org.herac.tuxguitar.editor.util.TGSyncProcessLocked$1.run(TGSyncProcessLocked.java:37)
        at org.herac.tuxguitar.app.synchronizer.TGSynchronizerControllerImpl$1$1.run(TGSynchronizerControllerImpl.java:29)
        at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
        at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
        at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4857)
        at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4409)
        at org.herac.tuxguitar.ui.swt.SWTApplication.start(SWTApplication.java:64)
        at org.herac.tuxguitar.app.TuxGuitar.createUIContext(TuxGuitar.java:117)
        at org.herac.tuxguitar.app.TuxGuitar.createApplication(TuxGuitar.java:102)
        at org.herac.tuxguitar.app.TGMainSingleton.launchTuxGuitar(TGMainSingleton.java:57)
        at org.herac.tuxguitar.app.TGMainSingleton.launchSingleton(TGMainSingleton.java:45)
        at org.herac.tuxguitar.app.TGMainSingleton.main(TGMainSingleton.java:35)
Exception in thread "Thread-10" java.lang.NullPointerException: Cannot invoke "org.herac.tuxguitar.action.TGActionContext.setAttribute(String, Object)" because "actionContext" is null
        at org.herac.tuxguitar.editor.action.TGActionProcessor.appendAttributes(TGActionProcessor.java:67)
        at org.herac.tuxguitar.editor.action.TGActionProcessor.fillActionContext(TGActionProcessor.java:57)
        at org.herac.tuxguitar.editor.action.TGActionProcessor.processOnCurrentThread(TGActionProcessor.java:75)
        at org.herac.tuxguitar.editor.action.TGActionProcessor.processOnCurrentThread(TGActionProcessor.java:88)
        at org.herac.tuxguitar.editor.action.TGActionProcessor$1.run(TGActionProcessor.java:98)
        at org.herac.tuxguitar.thread.TGPooledThreadHandler.processNext(TGPooledThreadHandler.java:66)
        at org.herac.tuxguitar.thread.TGPooledThreadHandler.run(TGPooledThreadHandler.java:86)
        at java.base/java.lang.Thread.run(Thread.java:1570)
```

**Comment by guiv42** [comment] 2024-04-05 17:38
tested in following configuration: Tuxguitar SWT e896ccce13a508e4cc5588db2e55c7b2a7a61c94, Linux openSuse tumbleweed (rolling release), KDE plasma 6
- X11 -> OK
- wayland -> issue reproduced with same error message, but **only once** !

I don't know why I cannot reproduce any more, but now it's difficult for me to investigate.

Note that exception is raised *outside* of TuxGuitar code, in SWT: it looks like an integration issue between SWT and wayland.
Possibly linked to this?
https://bugs.eclipse.org/bugs/show_bug.cgi?id=526357

> i'll try with the newest commits if requested.

@ojsl1 : yes please, I would appreciate if you can have a try with latest commit. Can you still reproduce it, systematically?
Until a solution is found, you can use JFX version

**Comment by Visne** [comment] 2024-04-13 04:31
The SWT bug was fixed in 4.15, but TuxGuitar 1.6.2 is still using SWT 4.13. Compiling TuxGuitar 1.6.2 but with SWT 4.26 fixes this bug for me.

**Comment by guiv42** [comment] 2024-04-13 08:23
OK, thanks for the feedback.
Since TuxGuitar Linux version now targets SWT [4.26](https://github.com/helge17/tuxguitar/blob/218140607f7f2455e1cd61e5a0245db81761665e/desktop/pom.xml#L304), can we close this issue now?

**Comment by Visne** [comment] 2024-04-13 08:51
I believe so!

**Comment by guiv42** [comment] 2024-04-13 10:37
OK, issue closed.
For wayland users: no need to rebuild from source, just use a recent [pre-release](https://github.com/helge17/tuxguitar/releases) that should be OK. If not, please re-open issue.

**Closed by guiv42** 2024-04-13 10:37 UTC
Labels: bug
