### ISSUE TITLE
Windows 10 - Dark themes dont work

### ISSUE THREAD

**Issue by ZelCloud** [helge17/tuxguitar#587] opened 2024-12-01 22:38 UTC
When selecting any of the dark themes from tux guitar skin settings none of the dark themes work the background removes blinding white and the icons turn white.

**Comment by guiv42** [comment] 2024-12-01 22:42
yes, it's an already known problem
Closing issue, it's (another) duplicate of #27

**Closed by guiv42** 2024-12-01 22:42 UTC
